# version: '3.8'
version: '3.4'
services:
  web:
    build: ./app
    command: bash -c 'sleep 5;  uvicorn app.main:app --host 0.0.0.0' #bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    # environment:
    #   - DATABASE_URL=postgresql://postgres:postgres@localhost/postgres
    depends_on:
      - db
    #restart: always
    networks:
      - custom
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    # expose:
    #   - 5432
    networks:
      - custom

networks:
  custom:
    driver: bridge