version: '3.4'

services:
  web:
    build: ./app
    command: bash -c 'sleep 2;  uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    networks:
      - custom

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - custom

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: always
    networks:
      - custom

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email --staging -d api-todo.kolotech.space
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    networks:
      - custom      

volumes:
  certbot-etc:
  certbot-var:

networks:
  custom:
    driver: bridge
